-- countries (260 records)
insert into countries (code, name, zone) values
  ('AD', 'ANDORRA', 'G'),
  ('AE', 'VERENIGDE ARABISCHE EMIRATEN', 'G'),
  ('AF', 'AFGHANISTAN', 'G'),
  ('AG', 'ANTIGUA EN BARBUDA', 'D'),
  ('AI', 'ANGUILLA', 'D'),
  ('AL', 'ALBANIË', 'G'),
  ('AO', 'ANGOLA', 'G'),
  ('AQ', 'ANTARTICA', 'G'),
  ('AR', 'ARGENTINIË', 'F'),
  ('AS', 'SAMAO (V.S.)', 'G'),
  ('AT', 'OOSTENRIJK', 'E'),
  ('AU', 'AUSTRALIË', 'H'),
  ('AW', 'ARUBA', 'C'),
  ('BB', 'BARBADOS', 'D'),
  ('BD', 'BANGLADESH', 'G'),
  ('BE', 'BELGIË', 'E'),
  ('BF', 'BURKINA FASSO', 'G'),
  ('BG', 'BULGARIJE', 'G'),
  ('BH', 'BAHREIN', 'G'),
  ('BI', 'BURUNDI', 'G'),
  ('BJ', 'BENIN', 'G'),
  ('BM', 'BERMUDA', 'D'),
  ('BN', 'BRUNEI DARUSSALAM', 'G'),
  ('BO', 'BOLIVIA', 'F'),
  ('BQ', 'BONAIRE', 'I'),
  ('BR', 'BRAZILIË', 'F'),
  ('BS', 'BAHAMA''S', 'D'),
  ('BT', 'BHUTAN', 'G'),
  ('BU', 'BIRMA', 'G'),
  ('BU', 'BUNKERING', 'G'),
  ('BV', 'BOUVET EILANDEN', 'G'),
  ('BW', 'BOTSWANA', 'G'),
  ('BY', 'WIT RUSLAND', 'G'),
  ('BZ', 'BELIZE', 'F'),
  ('CA', 'CANADA', 'E'),
  ('CC', 'COCOS EILANDEN', 'G'),
  ('CF', 'CENTRALE AFRIKA REPUBLIEK', 'G'),
  ('CG', 'KONGO', 'G'),
  ('CH', 'ZWITSERLAND', 'E'),
  ('CI', 'IVOORKUST', 'G'),
  ('CK', 'COOK EILANDEN', 'G'),
  ('CL', 'CHILI', 'F'),
  ('CM', 'KAMEROEN', 'G'),
  ('CN', 'CHINA', 'H'),
  ('CO', 'COLOMBIA', 'F'),
  ('CR', 'COSTA RICA', 'F'),
  ('CS', 'TSJECHO SLOWAKIJE', 'G'),
  ('CU', 'CUBA', 'G'),
  ('CUR', 'CURACAO', 'G'),
  ('CV', 'KAAPVERDISCHE EILANDEN', 'G'),
  ('CX', 'CHRISTMAS EILANDEN', 'G'),
  ('CY', 'CYPRUS', 'G'),
  ('DE', 'DUITSLAND', 'E'),
  ('DJ', 'DJIBOUTI', 'G'),
  ('DK', 'DENEMARKEN', 'E'),
  ('DM', 'DOMINICA', 'D'),
  ('DO', 'DOMINICAANSE REPUBLIEK', 'D'),
  ('DZ', 'ALGERIJE', 'G'),
  ('EC', 'ECUADOR', 'F'),
  ('EG', 'EGYPTE', 'G'),
  ('EH', 'WEST SAHARA', 'G'),
  ('ES', 'SPANJE', 'E'),
  ('ET', 'ETHIOPIË', 'G'),
  ('FI', 'FINLAND', 'E'),
  ('FJ', 'FIDJI EILANDEN', 'G'),
  ('FK', 'FALKLAND EILANDEN', 'G'),
  ('FM', 'MICRONESIË', 'G'),
  ('FO', 'FAROER EILANDEN', 'G'),
  ('FR', 'FRANKRIJK', 'E'),
  ('GA', 'GABON', 'G'),
  ('GB', 'VERENIGD KONINKRIJK', 'E'),
  ('GD', 'GRENADA', 'D'),
  ('GF', 'FRANS GUYANA', 'F'),
  ('GH', 'GHANA', 'G'),
  ('GI', 'GIBRALTAR', 'G'),
  ('GL', 'GROENLAND', 'G'),
  ('GM', 'GAMBIA', 'G'),
  ('GN', 'GUINEE', 'G'),
  ('GP', 'GUADALOUPE', 'D'),
  ('GQ', 'EQUATORIAAL GUINEE', 'G'),
  ('GR', 'GRIEKENLAND', 'E'),
  ('GT', 'GUATEMALA', 'F'),
  ('GU', 'GUAM', 'G'),
  ('GW', 'GUINEE-BISSAU', 'G'),
  ('GY', 'GUYANA', 'F'),
  ('HK', 'HONG KONG', 'H'),
  ('HM', 'HEARD EN MCDONALD EILANDEN', 'G'),
  ('HN', 'HONDURAS', 'F'),
  ('HT', 'HAITI', 'D'),
  ('HU', 'HONGARIJE', 'G'),
  ('ID', 'INDONESIË', 'H'),
  ('IE', 'IERLAND', 'E'),
  ('IL', 'ISRAËL', 'G'),
  ('IN', 'INDIA', 'H'),
  ('IQ', 'IRAK', 'G'),
  ('IR', 'IRAN', 'G'),
  ('IS', 'IJSLAND', 'G'),
  ('IT', 'ITALIË', 'E'),
  ('JM', 'JAMAICA', 'D'),
  ('JO', 'JORDANIË', 'G'),
  ('JP', 'JAPAN', 'H'),
  ('KE', 'KENIA', 'G'),
  ('KH', 'KAMPUCHEA', 'G'),
  ('KI', 'KIRIBATI EILANDEN', 'G'),
  ('KM', 'KOMOREN', 'G'),
  ('KN', 'ST.KITTS & LUCIA', 'D'),
  ('KP', 'KOREA', 'H'),
  ('KW', 'KOEWEIT', 'G'),
  ('KY', 'KAAYMAN EILANDEN', 'D'),
  ('LA', 'LAOS', 'G'),
  ('LB', 'LIBANON', 'G'),
  ('LC', 'ST.LUCIA', 'D'),
  ('LI', 'LICHTENSTEIN', 'E'),
  ('LK', 'SRI LANKA', 'G'),
  ('LR', 'LIBERIA', 'G'),
  ('LS', 'LESOTHO', 'G'),
  ('LU', 'LUXEMBURG', 'E'),
  ('LY', 'LIBIË', 'G'),
  ('MA', 'MAROKKO', 'G'),
  ('MC', 'MONACO', 'G'),
  ('MG', 'MADAGASCAR', 'G'),
  ('MH', 'MARSHALL EILANDEN', 'G'),
  ('ML', 'MALI', 'G'),
  ('MN', 'MONGOLIË', 'G'),
  ('MO', 'MACAO', 'G'),
  ('MP', 'NRD MARIANEN EILANDEN', 'G'),
  ('MQ', 'MARTINIQUE', 'D'),
  ('MR', 'MAURETANIË', 'G'),
  ('MS', 'MONTSERRAT', 'D'),
  ('MT', 'MALTA', 'G'),
  ('MU', 'MAURITIUS', 'G'),
  ('MV', 'MALEDIVEN', 'G'),
  ('MW', 'MALAWI', 'G'),
  ('MX', 'MEXICO', 'F'),
  ('MY', 'MALEISIË', 'H'),
  ('MZ', 'MOZAMBIQUE', 'G'),
  ('NA', 'NAMIBIË', 'G'),
  ('NC', 'NIEUW CALEDONIË', 'G'),
  ('NE', 'NIGER', 'G'),
  ('NF', 'NORFOLK EILANDEN', 'G'),
  ('NG', 'NIGERIA', 'G'),
  ('NI', 'NICARAQUA', 'F'),
  ('NL', 'NEDERLAND', 'E'),
  ('NO', 'NOORWEGEN', 'E'),
  ('NP', 'NEPAL', 'G'),
  ('NR', 'NAURO', 'G'),
  ('NU', 'NIUE', 'G'),
  ('NZ', 'NIEUW ZEELAND', 'H'),
  ('OM', 'OMAN', 'G'),
  ('ON', 'ONBEKEND VOOR LAND OORSPRONG', 'G'),
  ('PA', 'PANAMA', 'F'),
  ('PE', 'PERU', 'F'),
  ('PF', 'FRANS POLYNESIË', 'G'),
  ('PG', 'PAPUA NIEUW GUINEA', 'G'),
  ('PH', 'FILIPPIJNEN', 'H'),
  ('PK', 'PAKISTAN', 'G'),
  ('PL', 'POLEN', 'E'),
  ('PN', 'PITCAIRN', 'G'),
  ('PR', 'PUERTO RICO', 'D'),
  ('PT', 'PORTUGAL', 'E'),
  ('PW', 'PALAU', 'G'),
  ('PY', 'PARAGUAY', 'F'),
  ('QA', 'QATAR', 'G'),
  ('RE', 'REUNION', 'G'),
  ('RO', 'ROEMENIË', 'G'),
  ('RW', 'RWANDA', 'G'),
  ('SA', 'SAUDI-ARABIË', 'G'),
  ('SB', 'SALOMO EILANDEN', 'G'),
  ('SC', 'SEYCHELLEN', 'G'),
  ('SD', 'SOEDAN', 'G'),
  ('SE', 'ZWEDEN', 'E'),
  ('SG', 'SINGAPORE', 'H'),
  ('SH', 'ST. HELENA', 'G'),
  ('SL', 'SIERRA LEONE', 'G'),
  ('SM', 'SAN MARINO', 'G'),
  ('SN', 'SENEGAL', 'G'),
  ('SO', 'SOMALIË', 'G'),
  ('SR', 'SURINAME', 'F'),
  ('SU', 'RUSLAND', 'E'),
  ('SV', 'EL SALVADOR', 'F'),
  ('SX', 'ST. MAARTEN', 'I'),
  ('SY', 'SYRIË', 'G'),
  ('SZ', 'SWAZILAND', 'G'),
  ('TC', 'TURKS & CAICOS EILANDEN', 'D'),
  ('TD', 'TSJAAD', 'G'),
  ('TG', 'TOGO', 'G'),
  ('TH', 'THAILAND', 'H'),
  ('TK', 'TOKELAU', 'G'),
  ('TN', 'TUNESIË', 'G'),
  ('TO', 'TONGA', 'G'),
  ('TP', 'OOST TIMOR', 'G'),
  ('TR', 'TURKIJE', 'G'),
  ('TT', 'TRINIDAD & TOBAGO', 'D'),
  ('TV', 'TUVALU', 'G'),
  ('TW', 'TAIWAN', 'H'),
  ('TZ', 'TANZANIA', 'G'),
  ('UA', 'OEKRAÏNE', 'G'),
  ('UG', 'OEGANDA', 'G'),
  ('US', 'VERENIGDE STATEN', 'A'),
  ('UY', 'URUGUAY', 'F'),
  ('VA', 'VATICAAN', 'E'),
  ('VC', 'ST. VINCENT & GRENADINES', 'D'),
  ('VE', 'VENEZUELA', 'D'),
  ('VG', 'BRITSE MAAGDEN EILANDEN', 'D'),
  ('VI', 'AMERIKAANSE MAAGDEN EILANDEN', 'D'),
  ('VN', 'VIETNAM', 'G'),
  ('VU', 'VANUATA', 'G'),
  ('WS', 'SAMOA', 'G'),
  ('YD', 'JEMEN DEMOCRATS', 'G'),
  ('YE', 'JEMEN', 'G'),
  ('YU', 'JOEGOSLAVIË', 'G'),
  ('ZA', 'ZUID AFRIKA', 'G'),
  ('ZM', 'ZAMBIA', 'G'),
  ('ZW', 'ZIMBABWE', 'G'),
  ('ZR', 'ZAÏRE', 'G'),
  ('CW', 'CURACAO', 'G'),
  ('BQ', 'SABA', 'J'),
  ('BQ', 'SINT EUSTATIUS', 'J'),
  ('AX', 'LAND ISLANDS', NULL),
  ('AM', 'ARMENIA', NULL),
  ('AZ', 'AZERBAIJAN', NULL),
  ('BA', 'BOSNIA AND HERZEGOVINA', NULL),
  ('IO', 'BRITISH INDIAN OCEAN TERRITORY', NULL),
  ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', NULL),
  ('HR', 'CROATIA', NULL),
  ('CZ', 'CZECH REPUBLIC', NULL),
  ('ER', 'ERITREA', NULL),
  ('EE', 'ESTONIA', NULL),
  ('TF', 'FRENCH SOUTHERN TERRITORIES', NULL),
  ('GE', 'GEORGIA', NULL),
  ('GG', 'GUERNSEY', NULL),
  ('IM', 'ISLE OF MAN', NULL),
  ('JE', 'JERSEY', NULL),
  ('KZ', 'KAZAKHSTAN', NULL),
  ('KR', 'KOREA, REPUBLIC OF', NULL),
  ('KG', 'KYRGYZSTAN', NULL),
  ('LV', 'LATVIA', NULL),
  ('LT', 'LITHUANIA', NULL),
  ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC', NULL),
  ('YT', 'MAYOTTE', NULL),
  ('MD', 'MOLDOVA, REPUBLIC OF', NULL),
  ('ME', 'MONTENEGRO', NULL),
  ('MM', 'MYANMAR', NULL),
  ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', NULL),
  ('RU', 'RUSSIAN FEDERATION', NULL),
  ('BL', 'SAINT BARTHLEMY', NULL),
  ('MF', 'SAINT MARTIN (FRENCH PART)', NULL),
  ('PM', 'SAINT PIERRE AND MIQUELON', NULL),
  ('ST', 'SAO TOME AND PRINCIPE', NULL),
  ('RS', 'SERBIA', NULL),
  ('SK', 'SLOVAKIA', NULL),
  ('SI', 'SLOVENIA', NULL),
  ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL', NULL),
  ('SJ', 'SVALBARD AND JAN MAYEN', NULL),
  ('TJ', 'TAJIKISTAN', NULL),
  ('TL', 'TIMOR-LESTE', NULL),
  ('TM', 'TURKMENISTAN', NULL),
  ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', NULL),
  ('UZ', 'UZBEKISTAN', NULL),
  ('WF', 'WALLIS AND FUTUNA', NULL)
on conflict do nothing;

