-- iso_container_codes (57 records)
insert into iso_container_codes (code, description) values
  ('22BU', '20'' Bulk Container'),
  ('22GP', '20'' Dry Container'),
  ('22PC', '20'' Fixed Flat'),
  ('28VH', '20'' Half High Container'),
  ('22VH', '20'' Open Side Container'),
  ('22UT', '20'' Open Top Container'),
  ('22PF', '20'' Platform'),
  ('22RT', '20'' Reefer Container'),
  ('22TD', '20'' Tank'),
  ('22TN', '20'' Tank Container'),
  ('42PF', '40'' Flat Rack'),
  ('48TG', '40'' Tank for Gas'),
  ('42GP', '40'' standard dry Container'),
  ('42UT', '40'' Open Top Container'),
  ('42PC', '40'' Flat (Collapsible)'),
  ('42RT', '40'' Reefer Container'),
  ('42SN', '40'' Standard Dry Container'),
  ('42TD', '40'' Tank Container'),
  ('42HR', '40'' Insulated Container'),
  ('45GP', '40'' High Cube Container'),
  ('45RT', '45'' High Cube Reefer'),
  ('20GP', '20'' General Purpose'),
  ('20HR', '20'' Insulated Container'),
  ('20PF', '20'' Flat (Fixed ends) Container'),
  ('20TD', '20'' Tank Container'),
  ('20TG', '20'' Tank Container'),
  ('20TH', '20'' Tank Container'),
  ('22RC', '20'' Reefer Container (No food)'),
  ('22RS', '20'' Container (Built-in gen. f power sply or reef'),
  ('22SN', '20'' Named Cargo Container'),
  ('22TG', '20'' Tank Container'),
  ('22UP', '20'' Hardtop Container'),
  ('25GP', '20'' GP Container Overweight'),
  ('26GP', '20'' GP Container Overweight'),
  ('26HR', '20'' Insulated Container'),
  ('28TG', '20'' Tank for Gas Container'),
  ('28UT', '20'' Open Top Container (Half Height)'),
  ('28VH', '20'' VE Half Height  = 1448 MM Height Container'),
  ('29PL', '20'' Platform Container'),
  ('2EGP', '20'' Container GP without Vent Width 2.5M'),
  ('42PS', '40'' Flat Container (Space Saver)'),
  ('42RC', '40'' Reefer Container (no Food)'),
  ('42RS', '40'' Reefer Container (Diesel Gen.)'),
  ('42TG', '40'' Tank Container'),
  ('42TN', '40'' Tank Container'),
  ('42UP', '40'' Hardtop Container'),
  ('45BK', '40'' Bulk Container'),
  ('45PC', '40'' Flat Container (Collapsible)'),
  ('45RC', '40'' Reefer Container (No Food)'),
  ('45UT', '40'' Open Top Container'),
  ('45UP', '40'' High Cube Hardtop Container'),
  ('46HR', '40'' Insulated Container'),
  ('49PL', '40'' Platform Container'),
  ('4CGP', '40'' GP Container'),
  ('L0GP', '40'' High Cube Container'),
  ('L2GP', '40'' High Cube Container'),
  ('L5GP', '40'' High Cube Container')
on conflict do nothing;

